CREATE DATABASE IF NOT EXISTS BikeLocker COLLATE = 'utf8_general_ci';

CREATE TABLE COR
(
  CodCor INT NOT NULL,
  PRIMARY KEY (CodCor)
);

CREATE TABLE Funcionario (
    ID INT NOT NULL AUTO_INCREMENT,
    nome TEXT NOT NULL,
    senha TEXT NOT NULL,
    papel TEXT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Usuario
(
  CPF     INT     NOT NULL AUTO_INCREMENT,
  NOME    TEXT    NOT NULL,
  IMAGEM  BLOB    NOT NULL,
  LOCKER  INT     NOT NULL,
  CADEADO BOOLEAN NOT NULL,
  CHEGADA DATE    NOT NULL,
  SAIDA   DATE    NOT NULL,
  PRIMARY KEY (CPF)
);

CREATE TABLE Cor_Bike
(
  CPF    INT NOT NULL AUTO_INCREMENT,
  CodCor INT NOT NULL,
  FOREIGN KEY (CPF) REFERENCES Usuario (CPF),
  FOREIGN KEY (CodCor) REFERENCES COR (CodCor)
);